### ISSUE TITLE
Link on github

### ISSUE THREAD

**Issue by the-moog** [vscode-ext-studio/vscode-git-graph#5]
Your link on github still takes us to the increasingy outdated orgin of this fork.
I struggle to find your fork on the VSCode Marketplace. Any chance you can update your repo link?

![image](https://user-images.githubusercontent.com/3725802/216305452-d3616421-37f5-463d-bfa4-360fbf74f7fd.png)

**Comment by cweijan** [comment]
Has been corrected.
