### ISSUE TITLE
Missing "git graph" button

### ISSUE THREAD

**Issue by purple-emily** [vscode-ext-studio/vscode-git-graph#7]
Using the version that hasn't been updated in several years, there is a button:
![git graph button](https://user-images.githubusercontent.com/93710772/229248385-a4c24554-ebc9-4a63-9327-ca444913f02c.png)

Using this version, the button is missing:
![git graph button missing](https://user-images.githubusercontent.com/93710772/229248400-9c9648b0-b956-4a72-9bea-4157bb7a9ba9.png)

Can I bring this button back?

**Comment by purple-emily** [comment]
Further to this, the code is still in the src folder to display this and appears to be missing from the compiled extension. I believe this to be a bug

**Comment by cweijan** [comment]
Thanks for the feedback, I restored this icon in version 2.2.4.
